package database;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 * Data Access Object (DAO) responsible for executing CRUD operations
 * related to match histories. It abstracts the SQL logic away from the main application.
 * @implNote Data Access Object (DAO) Pattern
 */
public class MatchDAO {
    /**
     * Saves a list of match results to the database using batch processing.
     * <p>
     * This method opens a dedicated, short-lived connection to ensure thread-safety
     * without complex synchronization blocks. It processes all player records from
     * a single match in one network trip to the database.
     * * @param records A {@link List} of {@link ScoreRecord} objects containing
     * the data of all players who completed the match.
     */
    public void saveMatch(List<ScoreRecord> records) {
        // ID and Timestamp automatically generated by mySQL
        String sql = "INSERT INTO match_archive (nickname, score, player_count) VALUES (?, ?, ?)";

        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            for (ScoreRecord record : records) {
                // "?" substitution
                pstmt.setString(1, record.nickname());
                pstmt.setInt(2, record.score());
                pstmt.setInt(3, record.playerCount());
                pstmt.addBatch();
            }
            pstmt.executeBatch();

        } catch (SQLException e) {
            System.err.println("Error: " + e.getMessage());
        }
    }

    /**
     * Retrieves the top scores for a specific player count mode.
     * * @param playerCount The match mode (number of players).
     * @param limit The maximum number of rows to retrieve (e.g., 10 for Top 10).
     * @return A sorted {@link List} of {@link ScoreRecord} objects.
     */
    public List<ScoreRecord> getTopScores(int playerCount, int limit) {
        List<ScoreRecord> leaderboard = new ArrayList<>();
        String sql = "SELECT nickname, score, player_count, match_day " +
                     "FROM match_archive " +
                     "WHERE player_count = ? " +
                     "ORDER BY score DESC " +
                     "LIMIT ? ";


        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setInt(1, playerCount);
            pstmt.setInt(2, limit);

            try (ResultSet rs = pstmt.executeQuery()) {
                while (rs.next()) {
                    leaderboard.add(new ScoreRecord(
                            rs.getString("nickname"),
                            rs.getInt("score"),
                            rs.getInt("player_count"),
                            rs.getTimestamp("match_day").toLocalDateTime()
                    ));
                }
            }
        } catch (SQLException e) {
            System.err.println("Error fetching leaderboard: " + e.getMessage());
        }
        return leaderboard;
    }

    /**
     * Calculates the rank of this match of the player based on its score.
     * @param playerCount The match mode (number of players).
     * @param nickname The player name.
     * @param points The score achieved by the player in this match.
     * @return The 1-based rank position of the player.
     * @implNote This method counts how many players have an equal or higher score in the same player count mode.
     * This works because if there are two players with the same score, it takes the last one added, so the one just finished.
     */
    public int getPlayerRank(int playerCount, String nickname, int points) {
        String sql =
                "SELECT COUNT(*) AS rank_position " +
                "FROM match_archive " +
                "WHERE player_count = ? AND score >= ? ";

        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setInt(1, playerCount);
            pstmt.setInt(2, points);

            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    return rs.getInt("rank_position");
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return -1;
    }
}

